"""The headline demo: a support desk, because everyone understands tickets.

The audit scenario shows more of the machinery, but following it needs to know
what a control exception is and why fiscal periods do not line up. This one
needs nothing: urgent problems must be fixed in seven days, the live list says
eight are overdue, and Monday's summary says four. Which is right?

That disagreement is the whole point of the system, in one sentence.

Built as a domain pack from real files, so the demo also proves the thing it
claims: the engine is not wired to any particular domain.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from aios.config import Settings

# (ticket, team, priority, status, age_days, summary). Eight are overdue and
# Payments has three, the point at which a team is reported to the director.
TICKETS = [
    ("TKT-4101", "Payments", "urgent", "open", 31, "Card charged twice on retry"),
    ("TKT-4102", "Payments", "urgent", "open", 22, "Refund stuck in pending"),
    ("TKT-4116", "Payments", "urgent", "open", 8, "Payout batch stuck overnight"),
    ("TKT-4103", "Identity", "urgent", "open", 19, "Login loop after password reset"),
    ("TKT-4104", "Identity", "urgent", "open", 12, "SSO session drops on mobile"),
    ("TKT-4105", "Search", "urgent", "open", 9, "Empty results for exact match"),
    ("TKT-4106", "Mobile", "urgent", "open", 8, "Crash on photo upload"),
    ("TKT-4107", "Mobile", "urgent", "open", 8, "App freezes on checkout"),
    ("TKT-4108", "Search", "urgent", "open", 3, "Slow autocomplete"),
    ("TKT-4109", "Payments", "urgent", "closed", 2, "Invoice PDF missing"),
    ("TKT-4110", "Mobile", "normal", "open", 44, "Dark mode contrast"),
    ("TKT-4111", "Search", "normal", "open", 36, "Filters reset on back"),
    ("TKT-4112", "Identity", "normal", "open", 11, "Avatar upload fails"),
    ("TKT-4113", "Payments", "normal", "closed", 5, "Receipt email delayed"),
    ("TKT-4114", "Mobile", "low", "open", 61, "Typo on settings screen"),
    ("TKT-4115", "Search", "low", "closed", 4, "Sort order tooltip"),
]

SUPPORT_POLICY = """# Support policy

## How quickly problems must be fixed
An **urgent** problem must be fixed within **7 days** of being reported.
A **normal** problem must be fixed within 30 days. Low priority has no deadline.

## Overdue problems
A problem still open past its deadline is **overdue**. Overdue problems are
counted per team and reviewed every week. If any one team has **three or more
overdue urgent problems, it is reported to the director**.
"""

WEEKLY_SUMMARY = """# Weekly summary - Monday

Written on Monday morning from a copy of the problem list taken at 08:00.

- Overdue urgent problems: **4**. Payments 2, Identity 1, Search 1.
- No team has three, so nothing is being reported to the director.
- Mobile had none overdue when this copy was taken.

Note: this is a snapshot. Problems reported after 08:00 are not included.
"""

DOMAIN_PACK = """# Support desk demo, generated by `aios demo`.
#
# Paths use forward slashes. In TOML a backslash is an escape character.

name = "support"
description = "Weekly review of overdue support problems"

[capabilities]
research = "the support policy and last week's summary, via doc_search"
data = "the live list of problems, via describe_schema and named queries"
reporting = "a short review the support lead signs off"

[data_source]
kind = "files"
path = "{folder}"
allow_adhoc_queries = true

[documents]
path = "{folder}"

[prompts]
research = \"\"\"You are the Research agent for a support review.
You read the support policy and earlier summaries. Whenever you report a number
from a document, say when that document was written and what it covers.\"\"\"
data = \"\"\"You are the Data agent for a support review.
You answer from the live list of problems using named queries. Report only what
the rows support, and say how many problems each number is based on.\"\"\"
reporting = \"\"\"You are the Reporting agent for a support review.
You write the weekly review for the support lead. Say which teams must be
reported to the director, and name anything that could not be confirmed.\"\"\"

[queries.overdue_by_team]
description = "How many urgent problems are past the 7 day deadline, per team"
params = ["deadline_days"]
sql = \"\"\"
SELECT team, COUNT(*) AS overdue
FROM tickets
WHERE priority = 'urgent' AND status = 'open'
  AND CAST(age_days AS INTEGER) > :deadline_days
GROUP BY team ORDER BY overdue DESC
\"\"\"

[queries.overdue_detail]
description = "The individual urgent problems that are overdue"
params = ["deadline_days"]
sql = \"\"\"
SELECT ticket_id, team, age_days, summary
FROM tickets
WHERE priority = 'urgent' AND status = 'open'
  AND CAST(age_days AS INTEGER) > :deadline_days
ORDER BY CAST(age_days AS INTEGER) DESC
\"\"\"
"""


def build_support_demo(settings: Settings) -> tuple[Path, Path]:
    """Write the support dataset and its domain pack. Returns (folder, pack)."""
    folder = settings.data_dir / "support"
    folder.mkdir(parents=True, exist_ok=True)

    with (folder / "tickets.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ["Ticket ID", "Team", "Priority", "Status", "Age (days)", "Summary"]
        )
        writer.writerows(TICKETS)

    (folder / "support-policy.md").write_text(SUPPORT_POLICY, encoding="utf-8")
    (folder / "weekly-summary.md").write_text(WEEKLY_SUMMARY, encoding="utf-8")

    pack = settings.workspace / "domains" / "support.toml"
    pack.parent.mkdir(parents=True, exist_ok=True)
    pack.write_text(DOMAIN_PACK.format(folder=folder.resolve().as_posix()), encoding="utf-8")
    return folder, pack


# --- recorded model answers, so the demo runs with no key and no model --------

PLAN: dict[str, Any] = {
    "rationale": (
        "Establish the deadline, count overdue problems in the live list, check what last week's summary claimed, then reconcile and report."
    ),
    "tasks": [
        {
            "task_id": "t1_deadline_rule",
            "description": "Find the deadline for urgent problems, and when a team is reported to the director.",
            "agent": "research",
            "depends_on": [],
            "success_criteria": "The deadline and the director rule are quoted.",
            "critical": True,
            "requires_signoff": False,
        },
        {
            "task_id": "t2_live_count",
            "description": "Count urgent problems past the deadline in the live list, by team.",
            "agent": "data",
            "depends_on": ["t1_deadline_rule"],
            "success_criteria": "A per-team overdue count is produced.",
            "critical": True,
            "requires_signoff": False,
        },
        {
            "task_id": "t3_last_summary",
            "description": "Check what last week's summary said about overdue problems.",
            "agent": "research",
            "depends_on": ["t1_deadline_rule"],
            "success_criteria": "The number reported last week is stated.",
            "critical": True,
            "requires_signoff": False,
        },
        {
            "task_id": "t4_review",
            "description": "Write the weekly review for the support lead.",
            "agent": "reporting",
            "depends_on": ["t1_deadline_rule", "t2_live_count", "t3_last_summary"],
            "success_criteria": "Overdue counts, who must be reported, and open items are stated.",
            "critical": True,
            "requires_signoff": True,
        },
    ],
}

SCENARIO: dict[str, Any] = {
    "planner.plan": PLAN,
    "research.t1_deadline_rule.plan": {
        "calls": [
            {
                "tool": "doc_search",
                "arguments": [
                    {"name": "query", "value": "how quickly urgent problems must be fixed, overdue, director"},
                    {"name": "limit", "value": "3"},
                ],
                "purpose": "Find the deadline and the rule about the director.",
            }
        ]
    },
    "research.t1_deadline_rule.result": {
        "summary": (
            "The support policy says an urgent problem must be fixed within 7 days. A problem still open past that is overdue, and any team with three or more overdue urgent problems is reported to the director."
        ),
        "claims": [
            {"subject": "support policy", "metric": "deadline_days_urgent", "value": "7"},
            {"subject": "support policy", "metric": "report_to_director_at", "value": "3"},
        ],
        "confidence": 0.95,
        "evidence": ["support-policy.md"],
    },
    "data.t2_live_count.plan": {
        "calls": [
            {
                "tool": "describe_schema",
                "arguments": [],
                "purpose": "See what columns the problem list has.",
            },
            {
                "tool": "sql_query",
                "arguments": [
                    {"name": "query", "value": "overdue_by_team"},
                    {"name": "deadline_days", "value": "7"},
                ],
                "purpose": "Count overdue problems per team.",
            },
        ]
    },
    "data.t2_live_count.result": {
        "summary": (
            "The live list has 8 urgent problems open past the 7 day deadline: Payments 3, Mobile 2, Identity 2, Search 1. Payments has three, so it must be reported to the director."
        ),
        "claims": [
            {"subject": "overdue urgent problems", "metric": "count", "value": "8"},
            {"subject": "Payments", "metric": "overdue_urgent_problems", "value": "3"},
        ],
        "confidence": 0.94,
        "evidence": ["tickets.csv", "sql:overdue_by_team"],
    },
    "research.t3_last_summary.plan": {
        "calls": [
            {
                "tool": "doc_search",
                "arguments": [
                    {"name": "query", "value": "overdue urgent problems by team, weekly summary"},
                    {"name": "limit", "value": "2"},
                ],
                "purpose": "Find the number reported last week.",
            }
        ]
    },
    "research.t3_last_summary.result": {
        "summary": (
            "Last week's Monday summary reports 4 overdue urgent problems: Payments 2, Identity 1, Search 1, and says no team has reached three, so nothing goes to the director."
        ),
        "claims": [
            {"subject": "overdue urgent problems", "metric": "count", "value": "4"},
            {"subject": "Payments", "metric": "overdue_urgent_problems", "value": "2"},
        ],
        "confidence": 0.61,
        "evidence": ["weekly-summary.md"],
    },
    "research.t3_last_summary.plan@2": {
        "calls": [
            {
                "tool": "doc_search",
                "arguments": [
                    {
                        "name": "query",
                        "value": "snapshot taken Monday, problems reported after",
                    },
                    {"name": "limit", "value": "2"},
                ],
                "purpose": "Check when the summary was written and what it covers.",
            }
        ]
    },
    "research.t3_last_summary.result@2": {
        "summary": (
            "The summary is a Monday 08:00 snapshot and says so: problems reported after that are not included. Four more urgent problems have since gone past the deadline, so the live count of 8 replaces the reported 4. Payments moves from 2 to 3 and must now be reported to the director."
        ),
        "claims": [
            {"subject": "overdue urgent problems", "metric": "count", "value": "8"},
            {"subject": "Payments", "metric": "overdue_urgent_problems", "value": "3"},
        ],
        "confidence": 0.90,
        "evidence": ["weekly-summary.md", "tickets.csv"],
    },
    "reporting.t4_review.plan": {"calls": []},
    "reporting.t4_review.draft": {
        "title": "Which urgent problems are overdue?",
        "summary": (
            "Eight urgent problems are past the 7 day deadline. Payments has three, which is the point at which a team is reported to the director. Last week's summary showed four and nobody reported; that was a Monday snapshot taken before four more problems went overdue."
        ),
        "sections": [
            {
                "heading": "Where we are",
                "body": (
                    "8 urgent problems are open past the 7 day deadline set by the support policy.\n\n| Team | Overdue | Report to director |\n|---|---|---|\n| Payments | 3 | yes |\n| Mobile | 2 | no |\n| Identity | 2 | no |\n| Search | 1 | no |\n\nOldest: TKT-4101 (Payments, 31 days), TKT-4102 (Payments, 22 days), TKT-4103 (Identity, 19 days)."
                ),
            },
            {
                "heading": "Why this differs from last week's summary",
                "body": (
                    "The Monday summary shows 4 overdue and nobody reported. It is a snapshot taken at 08:00 and leaves out problems reported after that. Four more urgent problems have since gone past the deadline, including TKT-4116 in Payments, which is what moves Payments from 2 to 3. The live figure of 8 is the one to act on."
                ),
            },
            {
                "heading": "Open items",
                "body": (
                    "1. Payments has three overdue urgent problems and must be reported to the director.\n2. The weekly summary is written before the working day starts, so it will keep undercounting. Worth writing it later in the day, or generating it on demand."
                ),
            },
        ],
        "key_claims": [
            {"subject": "overdue urgent problems", "metric": "count", "value": "8"},
            {"subject": "Payments", "metric": "overdue_urgent_problems", "value": "3"},
            {"subject": "Payments", "metric": "must_report_to_director", "value": "true"},
        ],
        "confidence": 0.91,
        "open_questions": [
            "Confirm the director has been told about Payments."
        ],
    },
}
